#define RAC50
//#define RAC41
//#define RAC41_LAG
//#define RAC21
#ifdef RAC50

#define POT_PIN 11 // adc ADC1_CH3

#define SERVOA_PIN 14
#define SERVOA_LEDCCH 0

#define LED_PIN 21

#define MOTR_IN1_PIN 16
#define MOTR_IN2_PIN 17
#define MOTR_PWM_UNIT MCPWM_UNIT_0
#define MOTR_PWM_TIMER MCPWM_TIMER_0

#define MOTL_IN1_PIN 8
#define MOTL_IN2_PIN 18
#define MOTL_PWM_UNIT MCPWM_UNIT_0
#define MOTL_PWM_TIMER MCPWM_TIMER_1

#define MOTW_IN1_PIN 4
#define MOTW_IN2_PIN 5
#define MOTW_PWM_UNIT MCPWM_UNIT_0
#define MOTW_PWM_TIMER MCPWM_TIMER_2

#define MOTW2_IN1_PIN 6
#define MOTW2_IN2_PIN 15
#define MOTW2_PWM_UNIT MCPWM_UNIT_1
#define MOTW2_PWM_TIMER MCPWM_TIMER_0

#endif

#ifdef RAC41

#define POT_PIN 7 // adc ADC1_CH3

#define SERVOA_PIN 10
#define SERVOA_LEDCCH 0

#define LED_PIN 21

#define MOTR_IN1_PIN 16
#define MOTR_IN2_PIN 17
#define MOTR_PWM_UNIT MCPWM_UNIT_0
#define MOTR_PWM_TIMER MCPWM_TIMER_0

#define MOTL_IN1_PIN 8
#define MOTL_IN2_PIN 18
#define MOTL_PWM_UNIT MCPWM_UNIT_0
#define MOTL_PWM_TIMER MCPWM_TIMER_1

#define MOTW_IN1_PIN 4
#define MOTW_IN2_PIN 5
#define MOTW_PWM_UNIT MCPWM_UNIT_0
#define MOTW_PWM_TIMER MCPWM_TIMER_2

#define MOTW2_IN1_PIN 6
#define MOTW2_IN2_PIN 15
#define MOTW2_PWM_UNIT MCPWM_UNIT_1
#define MOTW2_PWM_TIMER MCPWM_TIMER_0

#endif

#ifdef RAC41_LAG

#define POT_PIN 7 // adc ADC1_CH3

#define SERVOA_PIN 10
#define SERVOA_LEDCCH 0

#define LED_PIN 21

#define MOTR_IN1_PIN 16
#define MOTR_IN2_PIN 17
#define MOTR_PWM_UNIT MCPWM_UNIT_0
#define MOTR_PWM_TIMER MCPWM_TIMER_0

#define MOTL_IN1_PIN 8
#define MOTL_IN2_PIN 18
#define MOTL_PWM_UNIT MCPWM_UNIT_0
#define MOTL_PWM_TIMER MCPWM_TIMER_1

#define MOTW_IN1_PIN 6
#define MOTW_IN2_PIN 15
#define MOTW_PWM_UNIT MCPWM_UNIT_0
#define MOTW_PWM_TIMER MCPWM_TIMER_2

#define MOTW2_IN1_PIN 5
#define MOTW2_IN2_PIN 4
#define MOTW2_PWM_UNIT MCPWM_UNIT_1
#define MOTW2_PWM_TIMER MCPWM_TIMER_0

#endif
#ifdef RAC21

#define POT_PIN 10 // adc ADC1_CH3

#define SERVOA_PIN 14
#define SERVOA_LEDCCH 0

#define LED_PIN 13

#define MOTR_IN1_PIN 4
#define MOTR_IN2_PIN 5
#define MOTR_PWM_UNIT MCPWM_UNIT_0
#define MOTR_PWM_TIMER MCPWM_TIMER_0

#define MOTL_IN1_PIN 6
#define MOTL_IN2_PIN 7
#define MOTL_PWM_UNIT MCPWM_UNIT_0
#define MOTL_PWM_TIMER MCPWM_TIMER_1

#define MOTW_IN1_PIN 16
#define MOTW_IN2_PIN 15
#define MOTW_PWM_UNIT MCPWM_UNIT_0
#define MOTW_PWM_TIMER MCPWM_TIMER_2

#define MOTW2_IN1_PIN 19
#define MOTW2_IN2_PIN 20
#define MOTW2_PWM_UNIT MCPWM_UNIT_1
#define MOTW2_PWM_TIMER MCPWM_TIMER_0

#endif